name: uniygopro_workspace
publish_to: none

environment:
  sdk: ^3.12.2

workspace:
  - packages/service_loader
  - packages/service_loader_gen
  - packages/ygo_data
  - packages/ygo_deck_mdpro3
  - packages/ygo_card_mycard
  - packages/ygo_card_baige
  - packages/ygo_banlist_mycard
  - packages/duelink
  - packages/duelink_websocket
  - packages/duelink_socket
  - packages/duelink_ai
  - packages/duelink_ai_edo
  - packages/ocgcore
  - packages/wasm_bridge
  - packages/ygo_storage
  - packages/ygo_deck_mycard
  - packages/ygo_agent
  - packages/ygo_agent_tflite
  - apps/uniygopro
  - apps/cardlive
  - apps/duelarena
  - apps/holoduel
  - apps/mdduel
  - apps/bloc_sample
  - apps/riverpod_sample
  - apps/duel_room1
