name: uniygopro_workspace
publish_to: none

environment:
  sdk: ^3.12.2

workspace:
  - packages/service_loader
  - packages/service_loader_gen
  - packages/ygo_data
  - packages/ygo_deck_mdpro3
  - packages/ygo_card_mycard
  - packages/ygo_card_baige
  - packages/ygo_card_ygoprodeck
  - packages/ygo_card_yugipedia
  - packages/ygo_banlist_mycard
  - packages/duelink
  - packages/duelink_websocket
  - packages/duelink_socket
  - packages/duelink_ai
  - packages/duelink_ai_edo
  - packages/ocgcore_edo
  - packages/ocgcore
  - packages/wasm_bridge
  - packages/ygo_storage
  - packages/ygo_deck_mycard
  - packages/duelink_ai_ygo_agent
  - packages/duelink_ai_ygo_agent_tflite
  - packages/duelink_ai_ygo_agent_http
  - packages/biz
  - apps/uniygopro
  - apps/deck_editor3
  - apps/duelarena
  - apps/holoduel
  - apps/mdduel
  - apps/duel_room1
  - apps/duel_room2
  - apps/duel_settings
  - apps/cardlive
  - apps/deck_editor1
