name: uniygo
publish_to: none

environment:
  sdk: ^3.12.2

workspace:
  - packages/applog
  - packages/service_loader
  - packages/service_loader_gen
  - packages/resource_data
  - packages/resource_deck_mdpro3
  - packages/resource_card_mycard
  - packages/resource_card_baige
  - packages/resource_card_ygoprodeck
  - packages/resource_card_yugipedia
  - packages/resource_banlist_mycard
  - packages/account_mycard
  - packages/duelink
  - packages/duelink_websocket
  - packages/duelink_socket
  - packages/duelink_ai
  - packages/duelink_ai_edo
  - packages/ocgcore_edo
  - packages/ocgcore
  - packages/wasm_bridge
  - packages/resource_storage
  - packages/resource_deck_mycard
  - packages/duelink_ai_ygo_agent
  - packages/duelink_ai_ygo_agent_tflite
  - packages/duelink_ai_ygo_agent_http
  - packages/biz
  - apps/debug
  - apps/uniygopro
  - modules/deck_editor1
  - modules/deck_editor3
  - apps/duelarena
  - apps/holoduel
  - apps/mdduel
  - modules/duel_room1
  - modules/duel_room2
  - modules/duel_room3
  - modules/ygo_settings
  - modules/cardlive
