name: duelink
description: Yu-Gi-Oh! duel network service interface for uniygopro.
version: 0.0.1
environment:
  sdk: ^3.12.2
resolution: workspace
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  service_loader:
    path: ../service_loader

dev_dependencies:
  test: ^1.25.0
  flutter_lints: ^6.0.0
