name: uniygopro
description: "A Yu-Gi-Oh! Pro game client."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  audioplayers: ^6.8.1
  flame: ^1.11.0
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  service_loader:
    path: ../../packages/service_loader
  duelink:
    path: ../../packages/duelink
  duelink_online:
    path: ../../packages/duelink_online
  duelink_lan:
    path: ../../packages/duelink_lan
  duelink_ai:
    path: ../../packages/duelink_ai
  ygo_data:
    path: ../../packages/ygo_data
  ygo_card_mycard:
    path: ../../packages/ygo_card_mycard
  ygo_banlist_mycard:
    path: ../../packages/ygo_banlist_mycard
  ygo_deck_mdpro3:
    path: ../../packages/ygo_deck_mdpro3
  go_router: ^14.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  service_loader_gen:
    path: ../../packages/service_loader_gen

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/decks/

