name: uniygopro
description: "A Yu-Gi-Oh! Pro game client."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  audioplayers: ^6.8.1
  flame: ^1.38.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  cardlive:
    path: ../../modules/cardlive
  deck_editor1:
    path: ../../modules/deck_editor1
  deck_editor3:
    path: ../../modules/deck_editor3
  duel_room1:
    path: ../../modules/duel_room1
  duel_room2:
    path: ../../modules/duel_room2
  duel_room3:
    path: ../../modules/duel_room3
  ygo_settings:
    path: ../../modules/ygo_settings
  resource_storage:
    path: ../../packages/resource_storage
  service_loader:
    path: ../../packages/service_loader
  biz:
    path: ../../packages/biz
  duelink:
    path: ../../packages/duelink
  duelink_websocket:
    path: ../../packages/duelink_websocket
  #  duelink_socket:
  #    path: ../../packages/duelink_socket
  duelink_ai:
    path: ../../packages/duelink_ai
  duelink_ai_edo:
    path: ../../packages/duelink_ai_edo
  resource_data:
    path: ../../packages/resource_data
  resource_card_baige:
    path: ../../packages/resource_card_baige
  resource_card_mycard:
    path: ../../packages/resource_card_mycard
  resource_banlist_mycard:
    path: ../../packages/resource_banlist_mycard
  resource_deck_mdpro3:
    path: ../../packages/resource_deck_mdpro3
  resource_deck_mycard:
    path: ../../packages/resource_deck_mycard
  account_mycard:
    path: ../../packages/account_mycard
  go_router: ^14.0.0
  http: ^1.2.1
  flutter_portal: ^1.1.4
  web_socket_channel: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  service_loader_gen:
    path: ../../packages/service_loader_gen

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/duel/
    - assets/sounds/ui/
