name: ygo_settings
description: "全局设置：决斗设置 + 决斗房渲染（2D/3D）偏好，持久化 + 设置弹窗。"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  shared_preferences: ^2.5.3
  biz:
    path: ../../packages/biz
  riverpod_annotation: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_generator: ^4.0.8

flutter:
  uses-material-design: true
