name: duel_room1
description: "从 uniygopro DuelRoomPage 拆出的决斗房间：等待室 + 决斗场地。"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^3.4.2
  audioplayers: ^6.8.1
  flame: ^1.38.0
  shared_preferences: ^2.5.3
  go_router: ^14.0.0
  http: ^1.2.1
  flutter_portal: ^1.1.4
  flutter_animate: ^4.5.0
  biz:
    path: ../../packages/biz
  duelink:
    path: ../../packages/duelink
  resource_data:
    path: ../../packages/resource_data
  cardlive:
    path: ../cardlive
  flutter_scene: ^0.21.1
  collection: ^1.19.0
  riverpod_annotation: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_generator: ^4.0.8

flutter:
  uses-material-design: true
  generate: true
