/// Golden equivalence test: replays every golden duel through the Dart
/// [predict] with a replay `ModelFn` backed by the captured tensors, and
/// requires bit-exact agreement with the upstream Python pipeline at every
/// observable point:
///
///  - rstate before each step vs `rstate1_before`/`rstate2_before`
///  - all four observation tensors (cards_/global_/actions_/h_actions_)
///    vs the npz, including shortcut steps (via `state.lastModelInput`)
///  - full legal-action field dump vs `actions.json`
///  - probs/responses/can_finish/win_rate vs `pred.json`
///  - chosen action = first argmax, threaded as `prev_action_idx`
///
/// Golden data: `tools/ygo_agent_golden/golden` (generated by
/// `tools/ygo_agent_golden/gen_golden.py`).
@Tags(['golden'])
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:ygo_agent/ygo_agent.dart';

import 'npy.dart';

const goldenRoot = '../../tools/ygo_agent_golden/golden';
const codeListPath = '../../tools/ygo_agent_golden/models/code_list.txt';

void expectUint8Bytes(Uint8List actual, Uint8List expected, String what) {
  expect(actual.length, expected.length, reason: '$what: length');
  for (var i = 0; i < actual.length; i++) {
    if (actual[i] != expected[i]) {
      fail('$what differs at byte $i: ${actual[i]} != ${expected[i]}');
    }
  }
}

Uint8List float32Bytes(Float32List x) =>
    x.buffer.asUint8List(x.offsetInBytes, x.lengthInBytes);

void expectFloat32Bytes(Float32List actual, Float32List expected, String what) {
  expectUint8Bytes(float32Bytes(actual), float32Bytes(expected), what);
}

Map<String, dynamic> readJsonMap(String path) =>
    jsonDecode(File(path).readAsStringSync()) as Map<String, dynamic>;

List<dynamic> readJsonList(String path) =>
    jsonDecode(File(path).readAsStringSync()) as List<dynamic>;

/// JSON-serializable view of a [LegalAction], keyed exactly like the
/// upstream pydantic dump (`LegalAction.json()`).
Map<String, Object?> actionRow(LegalAction a) => {
      'msg': a.msg.value,
      'spec': a.spec,
      'act': a.act.value,
      'phase': a.phase.value,
      'finish': a.finish,
      'position': a.position.value,
      'effect': a.effect,
      'number': a.number,
      'place': a.place.value,
      'attribute': a.attribute.value,
      'card_index': a.cardIndex,
      'card_id': a.cardId,
      'response': a.response,
      'can_finish': a.canFinish,
    };

void main() {
  final codeListFile = File(codeListPath);
  if (!codeListFile.existsSync()) {
    throw StateError('missing $codeListPath; run tools/ygo_agent_golden first');
  }
  final codeList = CodeList.parse(codeListFile.readAsStringSync());
  final duelDirs = Directory(goldenRoot)
      .listSync()
      .whereType<Directory>()
      .map((d) => d.path)
      .toList()
    ..sort();
  if (duelDirs.isEmpty) {
    throw StateError('no golden duels found under $goldenRoot');
  }

  test('golden set is non-trivial', () {
    expect(duelDirs.length, greaterThanOrEqualTo(20));
  });

  for (final duelPath in duelDirs) {
    final duelId = duelPath.split(Platform.pathSeparator).last;

    test('golden duel: $duelId', () {
      final stepInputs = Directory(duelPath)
          .listSync()
          .whereType<File>()
          .map((f) => f.path)
          .where((p) => p.endsWith('_input.json'))
          .toList()
        ..sort();
      expect(stepInputs, isNotEmpty);

      final state = PredictState(codeList: codeList);
      int? prevIdx;

      for (final inputPath in stepInputs) {
        final prefix =
            inputPath.substring(0, inputPath.length - '_input.json'.length);
        final stepId = prefix.split(Platform.pathSeparator).last;
        final reason = '$duelId/$stepId';

        final input = Input.fromJson(readJsonMap(inputPath));
        final pred = readJsonMap('${prefix}_pred.json');
        final npz = parseNpz(File('${prefix}_tensors.npz').readAsBytesSync());
        final shortcut = pred['single_action_shortcut'] as bool;

        // ── rstate entering this step ──
        expectFloat32Bytes(
            state.rstate.$1,
            npz['rstate1_before']!.asFloat32(context: '$reason rstate1_before'),
            '$reason rstate1_before');
        expectFloat32Bytes(
            state.rstate.$2,
            npz['rstate2_before']!.asFloat32(context: '$reason rstate2_before'),
            '$reason rstate2_before');

        // ── replay model ──
        var modelCalled = false;
        ModelOutput modelFn(RState rstate, ModelInput mi) {
          modelCalled = true;
          return ModelOutput(
            rstate: (
              npz['rstate1_after']!
                  .asFloat32(context: '$reason rstate1_after'),
              npz['rstate2_after']!
                  .asFloat32(context: '$reason rstate2_after'),
            ),
            probs:
                npz['probs_raw']!.asFloat32Doubles(context: '$reason probs_raw'),
            value: npz['value']!.asScalarFloat32(context: '$reason value'),
          );
        }

        final resp = predict(modelFn, input, prevIdx, state);
        expect(modelCalled, !shortcut, reason: '$reason model called');

        // ── observation tensors (set on every step, shortcut included) ──
        final mi = state.lastModelInput!;
        expectUint8Bytes(mi.cards,
            npz['cards_']!.asUint8(context: '$reason cards_'), '$reason cards_');
        expectUint8Bytes(mi.global,
            npz['global_']!.asUint8(context: '$reason global_'), '$reason global_');
        expectUint8Bytes(mi.actions,
            npz['actions_']!.asUint8(context: '$reason actions_'),
            '$reason actions_');
        expectUint8Bytes(mi.hActions,
            npz['h_actions_']!.asUint8(context: '$reason h_actions_'),
            '$reason h_actions_');

        // ── legal actions, field by field vs actions.json ──
        final legal = getLegalActions(input.actionMsg, codeList);
        expect(legal.length, pred['n_legal_actions'],
            reason: '$reason n_legal_actions');
        expect(shortcut, legal.length == 1, reason: '$reason shortcut flag');
        final specInfos = encodeCards(input.cards, codeList).specInfos;
        encodeLegalActions(legal, specInfos); // Fills card_index/card_id.
        final expectedActions = readJsonList('${prefix}_actions.json');
        expect(legal.length, expectedActions.length,
            reason: '$reason actions.json length');
        for (var i = 0; i < legal.length; i++) {
          expect(actionRow(legal[i]), expectedActions[i],
              reason: '$reason action[$i]');
        }

        // ── MsgResponse vs pred.json ──
        expect(resp.winRate, (pred['win_rate'] as num).toDouble(),
            reason: '$reason win_rate');
        final expProbs = [
          for (final e in pred['probs'] as List) (e as num).toDouble(),
        ];
        final expResponses = [for (final e in pred['responses'] as List) e as int];
        final expCanFinish = [
          for (final e in pred['can_finish'] as List) e as bool,
        ];
        expect(resp.actionPreds.length, expProbs.length,
            reason: '$reason n_preds');
        for (var i = 0; i < expProbs.length; i++) {
          expect(resp.actionPreds[i].prob, expProbs[i],
              reason: '$reason prob[$i]');
          expect(resp.actionPreds[i].response, expResponses[i],
              reason: '$reason response[$i]');
          expect(resp.actionPreds[i].canFinish, expCanFinish[i],
              reason: '$reason can_finish[$i]');
        }

        // ── choice: first argmax, threaded to the next step ──
        var chosen = 0;
        for (var i = 1; i < expProbs.length; i++) {
          if (expProbs[i] > expProbs[chosen]) {
            chosen = i;
          }
        }
        expect(chosen, pred['chosen_idx'], reason: '$reason chosen_idx');
        expect(expResponses[chosen], pred['chosen_response'],
            reason: '$reason chosen_response');
        expect(pred['prev_action_idx'], prevIdx,
            reason: '$reason prev_action_idx');
        prevIdx = chosen;
      }
    });
  }
}
