/// Verifies the [PyIntSet] CPython-set simulator and the select_sum
/// combination pipeline against ground truth generated by real CPython 3.11
/// (`tools/ygo_agent_golden/gen_pysim_truth.py`).
@Tags(['golden'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:ygo_agent/src/legal_actions.dart';

void main() {
  late Map<String, dynamic> truth;

  setUpAll(() {
    final file = File('test/data/pysim_truth.json');
    expect(file.existsSync(), isTrue,
        reason: 'run tools/ygo_agent_golden/gen_pysim_truth.py first');
    truth = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  });

  test('set construction matches CPython iteration order', () {
    final cases = (truth['build'] as List).cast<List<dynamic>>();
    for (final c in cases) {
      final values = (c[0] as List).cast<int>();
      final expected = (c[1] as List).cast<int>();
      final s = PyIntSet.of(values);
      expect(s.iter().toList(), expected, reason: 'insert=$values');
      expect(s.used, expected.length, reason: 'insert=$values');
    }
  });

  test('set difference matches CPython iteration order', () {
    final cases = (truth['diff'] as List).cast<List<dynamic>>();
    for (final c in cases) {
      final cList = (c[0] as List).cast<int>();
      final selected = (c[1] as List).cast<int>();
      final expected = (c[2] as List).cast<int>();
      final result = PyIntSet.of(cList).difference(PyIntSet.of(selected));
      expect(result.iter().toList(), expected,
          reason: 'c=$cList selected=$selected');
      if (expected.isEmpty) {
        expect(result.firstIter, throwsStateError,
            reason: 'c=$cList selected=$selected');
      } else {
        expect(result.firstIter(), expected.first,
            reason: 'c=$cList selected=$selected');
      }
    }
  });

  test('select_sum pipeline matches CPython action order', () {
    final cases = (truth['sum'] as List).cast<List<dynamic>>();
    for (final c in cases) {
      final cardLevels = [
        for (final e in c[0] as List) (e as List).cast<int>(),
      ];
      final levelSum = c[1] as int;
      final selected = (c[2] as List).cast<int>();
      final expected = c[3] as Map<String, dynamic>;
      final reason = 'levels=$cardLevels sum=$levelSum selected=$selected';

      if (expected['error'] == 'empty') {
        expect(
            () => selectSumActionOrder(cardLevels, levelSum, selected),
            throwsA(isA<NotSupportedException>()),
            reason: reason);
        continue;
      }
      final actions = (expected['actions'] as List)
          .map((e) => ((e as List)[0] as int, e[1] as bool))
          .toList();
      expect(selectSumActionOrder(cardLevels, levelSum, selected), actions,
          reason: reason);
    }
  });
}
