name: duelink_ai
description: AI local duel implementation for duelink using OCGCore engine.
version: 0.0.1
environment:
  sdk: ^3.12.2
resolution: workspace
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  duelink:
    path: ../duelink
  duelink_ai_ygo_agent:
    path: ../duelink_ai_ygo_agent
  duelink_ai_ygo_agent_tflite:
    path: ../duelink_ai_ygo_agent_tflite
  duelink_ai_ygo_agent_http:
    path: ../duelink_ai_ygo_agent_http
  async: ^2.11.0
  service_loader:
    path: ../service_loader
  ocgcore:
    path: ../ocgcore
  ygo_data:
    path: ../ygo_data


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.2.1
