name: deck_editor3
description: "卡组中心：卡组市场（MDPro3 卡组广场）+ 我的卡组 + 全新组卡编辑器。"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  provider: ^6.1.2
  biz:
    path: ../../packages/biz
  account_mycard:
    path: ../../packages/account_mycard
  resource_data:
    path: ../../packages/resource_data
  resource_card_mycard:
    path: ../../packages/resource_card_mycard
  resource_deck_mycard:
    path: ../../packages/resource_deck_mycard
  resource_deck_mdpro3:
    path: ../../packages/resource_deck_mdpro3
  resource_banlist_mycard:
    path: ../../packages/resource_banlist_mycard
  service_loader:
    path: ../../packages/service_loader
  riverpod_annotation: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_generator: ^4.0.8

flutter:
  uses-material-design: true
