name: deck_editor3
description: "卡组中心：卡组市场（MDPro3 卡组广场）+ 我的卡组 + 全新组卡编辑器。"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  provider: ^6.1.2
  biz:
    path: ../../packages/biz
  account_mycard:
    path: ../../packages/account_mycard
  ygo_data:
    path: ../../packages/ygo_data
  ygo_card_mycard:
    path: ../../packages/ygo_card_mycard
  ygo_deck_mycard:
    path: ../../packages/ygo_deck_mycard
  ygo_deck_mdpro3:
    path: ../../packages/ygo_deck_mdpro3
  ygo_banlist_mycard:
    path: ../../packages/ygo_banlist_mycard
  service_loader:
    path: ../../packages/service_loader

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
