// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sPAV7E0bvCMsFkdnciDICZkhWP5u84E',
    appId: '1:394905982403:web:715e6d90b5f2dcc524d976',
    messagingSenderId: '394905982403',
    projectId: 'spacecraft-67664',
    authDomain: 'spacecraft-67664.firebaseapp.com',
    storageBucket: 'spacecraft-67664.appspot.com',
    measurementId: 'G-1SNEQMP7C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtCtTEK_kk3AdjO-aRm-tkgzuzMVo6Rg',
    appId: '1:394905982403:android:6605ad64c59f2a4a24d976',
    messagingSenderId: '394905982403',
    projectId: 'spacecraft-67664',
    storageBucket: 'spacecraft-67664.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQetjrA1qL96KJkvJLB75OqREOpxWs7yQ',
    appId: '1:394905982403:ios:04cc0c1f33d674ac24d976',
    messagingSenderId: '394905982403',
    projectId: 'spacecraft-67664',
    storageBucket: 'spacecraft-67664.appspot.com',
    iosBundleId: 'com.e.uniygopro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQetjrA1qL96KJkvJLB75OqREOpxWs7yQ',
    appId: '1:394905982403:ios:04cc0c1f33d674ac24d976',
    messagingSenderId: '394905982403',
    projectId: 'spacecraft-67664',
    storageBucket: 'spacecraft-67664.appspot.com',
    iosBundleId: 'com.e.uniygopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7sPAV7E0bvCMsFkdnciDICZkhWP5u84E',
    appId: '1:394905982403:web:7a949442a642a9bf24d976',
    messagingSenderId: '394905982403',
    projectId: 'spacecraft-67664',
    authDomain: 'spacecraft-67664.firebaseapp.com',
    storageBucket: 'spacecraft-67664.appspot.com',
    measurementId: 'G-4H2YC2GPFM',
  );
}
